### ISSUE TITLE
Pulse Potter displays incorrect RfRaw information

### ISSUE THREAD

**Issue by ArkBrj** [Slipn3r/flipper-dashboard#57]
While observing my IR capture (see attached) I noticed that Pulse Plotter displays weird RfRaw info (see [1] below).
Specifically I am talkin about the dot at the beginning: "AAB1030B.6D14".
A brief investigation revealed that the problem is in the last line of the following code snippet:

            create_rfraw(t) {
                const e = this.hist_timings;
                if (e.bins.length < 1)
                    return "";
                if (e.bins.length > 8)
                    return "";
                if (t.length > 494)
                    return "";
                const s = new O;
                for (const h of e.bins)
                    s.pushWord(h.mean);

The problem is that h.mean is a float while pushWord seems to expect an int. When pushWord gets a float as the input, it generates a float representation of the number which potentially includes a dot.

[1]
RfRaw (rx): AAB1030B.6D1417582809291929291919291919291919292919291919192929292929292929191919191919291919291919192919292919292929080929192929191929191929191929291929191919292929292929292919191919191929191929191919291929291929292908092929192919291929192929191929192919191919191919191919191919191919191919191919191919192929291929155
RfRaw (tx): AAB09D03010B.6D1417582809291929291919291919291919292919291919192929292929292929191919191919291919291919192919292919292929080929192929191929191929191929291929191919292929292929292919191919191929191929191919291929291929292908092929192919291929192929191929192919191919191919191919191919191919191919191919191919192929291929155
Bits: {225} 00 / FF FF FF FF FF FF 80 / 00 / FF FF FF FF FF FF 80 / 00 / FF FF FF FF FF FF 8

[AC.ir.txt](https://github.com/flipperdevices/lab.flipper.net/files/14338035/AC.ir.txt)

**Comment by mlyubimov** [comment]
Hi! Thanks for finding the problem! 
We'll take a look and let you know the results

**Comment by Slipn3r** [comment]
Fixed, you can try that out at [https://lab.flipp.dev/pulse-plotter](https://lab.flipp.dev/pulse-plotter).
Will get to production in the next release
