### ISSUE TITLE
Docker container empty App list

### ISSUE THREAD

**Issue by iamnotaskynet** [Slipn3r/flipper-dashboard#58]
### Does somebody know why it's empty?
![image](https://github.com/flipperdevices/lab.flipper.net/assets/14093790/c1c47424-15e4-4171-a0b9-8a04efa4c716)

### Steps to reproduce:

`git clone https://github.com/flipperdevices/lab.flipper.net.git`

`cd lab.flipper.net.git`

`docker build -t flipper-lab -f Dockerfile-prod . --network host # in case apk not worked, it helped me`

`docker run -it -p 127.0.0.1:8080:80 flipper-lab`

### What I want to achieve?

Same possibility of installing apps as in https://lab.flipper.net/apps

![image](https://github.com/flipperdevices/lab.flipper.net/assets/14093790/23a7821f-17c1-49c1-846e-f4f13d29cc02)

**Comment by iamnotaskynet** [comment]
![image](https://github.com/flipperdevices/lab.flipper.net/assets/14093790/62651694-9b0c-48f5-bd2b-10e084ee85f3)

So it's because CORS, there should be a way to proxy request from Browser to Container and to the endpoint, perhaps to allow this in nginx.conf

UPD: Or somewhere in Vue app.

**Comment by mlyubimov** [comment]
Hello! CORS will not allow you to connect to our catalog from 127.0.0.1. Run docker on localhost. The code below should do it

`docker run -it -p 8080:80 flipper-lab`

The code for installing apps can be found at the path `frontend/src/stores/apps.js`. You need the `installApp()` function
