### ISSUE TITLE
it won't list serial ports (steam deck)

### ISSUE THREAD

**Issue by DavidIgor** [Slipn3r/flipper-dashboard#59]
chrome browser on my steamdeck won't connect to my flipper! it won't display connected devices via usb .

**Comment by ghost** [comment]
its an issue with linux in general, I'm trying to find a solution too.

**Comment by DavidIgor** [comment]
I had same problem with qFlipper , but then I downloaded directly from github and it works now ...

**Comment by Slipn3r** [comment]
This is caused by lack of permissions (udev rules). Your browser needs to access a physical port outside of the sandbox.
